### ISSUE TITLE
PROOF OF CONCEPT: basic CRUD functionality

### ISSUE THREAD

**Issue by timgoalen** [timgoalen/magical-places-london#10]
As a **developer** I can **implement basic CRUD functionality** so that I can **test my approach**.

## Tasks
In the admin panel, the ability to:
- [x] - Submit new 'place' by name & coordinates
- [x] - Update new 'place'
- [x] - Delete new 'place'
In the Map page:
- [x] - View a newly added place
- [x] - Open a place in a dedicated place_detail URL
Comments:
- [x] - Add prototype comments functionality
