### ISSUE TITLE
USER STORY: Map View

### ISSUE THREAD

**Issue by timgoalen** [timgoalen/magical-places-london#26]
As a **user** I can **view all places on a map** to easily **see which places are nearby**.

## Acceptance criteria
* Map page
* Saved places to show up as pins on the map
* Saved places to have photo and title in map popup info box

## Tasks
- [x] Create home.html
- [x] Setup Google Maps API
- [x] Pass list of places from Django to the template as JSON
- [x] Pass JSON to JavaScript, to show as pins on Google map
