### ISSUE TITLE
USER STORY: List View

### ISSUE THREAD

**Issue by timgoalen** [timgoalen/magical-places-london#27]
As a **user** I can **view a list of the places** to **see titles, pictures and how many comments have been left**.

## Acceptance criteria
* List view page
* Photo is displayed
* Title is displayed
* Comment count is displayed

## Tasks
- [x] Create list_view.html
- [x] Display dtat from Django in the template: title & comment count.
- [x] Get photo from Google Places API
