### ISSUE TITLE
USER STORY: Deployment

### ISSUE THREAD

**Issue by timgoalen** [timgoalen/magical-places-london#3]
As a **developer** I can **deploy the website** so that it's **accessible to users***.

## Acceptance criteria
* Functioning deployment to Heroku

## Tasks
- [x] Setup Django project & app
- [x] Link PostgreSQL via Elephant SQL
- [x] Link Cloudinary (for assets and static files)
- [x] Creta Config Vars in Heroku 
- [x] Hide SECRET_KEY in env.py
- [x] Add domain to ALLOWED_HOSTS
- [x] Install gunicorn
- [x] Create Procfile
