### ISSUE TITLE
USER STORY: Create Comment.

### ISSUE THREAD

**Issue by timgoalen** [timgoalen/magical-places-london#30]
As a **user** I can **leave a comment on a place**, to **share my experience with other users**.

## Acceptance criteria
* Once signed in, a user can leave a comment on a place.
* User receives successful feedback message
* Comment form is in the detail view

## Tasks
- [x] Create comment model
- [x] Create comment form
- [x] Update place_detail to include comment form
