### ISSUE TITLE
USER STORY: Edit Comment

### ISSUE THREAD

**Issue by timgoalen** [timgoalen/magical-places-london#32]
As a user I can edit my comments, to correct or add information.

## Acceptance criteria
* User can edit their own comments (not others)

## Tasks
- [x] Create comment_edit template
- [x] Create comment_edit form
- [x] Set up authentication & permissions
