### ISSUE TITLE
USER STORY: Delete Comment

### ISSUE THREAD

**Issue by timgoalen** [timgoalen/magical-places-london#33]
As a user I can delete my comments, to allow me to change my mind.

## Acceptance criteria
* User can delete ONLY their own comments

## Tasks
- [x] Create comment_delete template
- [x] Create comment_delete form
- [x] Set up authentication & permissions
