### ISSUE TITLE
USER STORY: Add a Place

### ISSUE THREAD

**Issue by timgoalen** [timgoalen/magical-places-london#36]
As a user I can easily add a place by typing its name, to share my recommendation with other users.

## Acceptance criteria
* Search bar with autocomplete
* Selected place is shown with name, address and photo
* User has the option to Save or Cancel

## Tasks
- [x] Set up Google Places autocomplete
- [x] Set up a hidden form that is filled out in the background by the place details from Google
- [x] Create a Place model
- [x] Create an 'add-place' view
- [x] Create an 'add-place' form
